_wandb:
    value:
        cli_version: 0.25.1
        e:
            hq9d2klkt5t08gf7ij3b8kz7wty2w62m:
                args:
                    - --args.output_dir
                    - ./exps/zod_dinov3
                    - --args.dataset_file
                    - zod
                    - --args.zod_path
                    - /root/zod-dataset
                    - --args.backbone
                    - dinov3_vit_small
                    - --args.pretrained_backbone_path
                    - ./pt_models/dinov3_vit_small.safetensors
                    - --args.batch_size
                    - "12"
                    - --args.num_workers
                    - "28"
                    - --args.epochs
                    - "12"
                    - --args.with_box_refine
                    - --args.two_stage
                    - --args.mixed_selection
                    - --args.look_forward_twice
                    - --args.num_queries_one2one
                    - "300"
                    - --args.num_queries_one2many
                    - "1500"
                    - --args.lr
                    - "2e-4"
                    - --args.lr_drop
                    - "10"
                    - --args.use_layerwise_decay
                    - --args.lr_decay_rate
                    - "0.9"
                    - --args.weight_decay
                    - "0.05"
                    - --args.norm_type
                    - pre_norm
                    - --args.num_feature_levels
                    - "1"
                    - --args.decoder_type
                    - global_rpe_decomp
                    - --args.decoder_rpe_type
                    - linear
                    - --args.proposal_feature_levels
                    - "4"
                    - --args.proposal_in_stride
                    - "16"
                    - --args.drop_path_rate
                    - "0.1"
                    - --args.k_one2many
                    - "6"
                    - --args.lambda_one2many
                    - "1.0"
                    - --args.dropout
                    - "0.0"
                    - --args.wd_norm_mult
                    - "0.0"
                    - --args.warmup
                    - "1000"
                    - --args.use_wandb
                    - --args.wandb_name
                    - zod_dinov3_vit_small_run_fixed_1
                cpu_count: 192
                cpu_count_logical: 384
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "943327023104"
                        used: "697572175872"
                email: baldassarre.fr@gmail.com
                executable: /root/Plain-DETR-v2/.venv/bin/python
                git:
                    commit: e5358629c87ed93e72f0cb4d110cc4538b75fb63
                    remote: git@gitlab.ice.ri.se:francesco.baldassarre/thesis-fedSSL.git
                gpu: NVIDIA H100 NVL
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-687010cd-b31b-c464-3ad0-babfb1d0db32
                host: francesco-754cd6c7fb-jwcdj
                memory:
                    total: "1622917971968"
                os: Linux-5.15.0-164-generic-x86_64-with-glibc2.31
                program: -m plain_detr.main
                python: CPython 3.12.12
                root: /root/Plain-DETR-v2
                startedAt: "2026-04-17T13:28:08.158913Z"
                writerId: hq9d2klkt5t08gf7ij3b8kz7wty2w62m
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 13
                - 14
                - 61
            "4": 3.12.12
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
